version: "3"
services:
  nginx: #服务名称
  image: nginx:latest  #镜像名称
  ports:
    - 80:80
  volumes: #挂载
    - /usr/local/nginx/html:/usr/share/nginx/html
    - /usr/local/nginx/nginx.conf:/etc/nginx/nginx.conf
  privileged: true #这个必须要，解决nginx的文件调用权限问题

  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    entrypoint: #指定用户root的密码
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:latest
    ports:
      - "6379"
  blog:
    image: blog:latest
    build: .
    ports:
      - 8083:8083
    depends_on:
      - mysql
      - redis