package com.zy.blog.dao;


import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.core.toolkit.Constants;
import com.zy.blog.model.Blog;
import com.zy.blog.model.vo.BlogVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BlogMapper extends BaseMapper<Blog> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
    Blog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
    List<Blog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
    int updateByPrimaryKey(Blog record);

//    IPage<Blog> getTablePage(Page<Blog> page, @Param(Constants.WRAPPER)
//            QueryWrapper<Blog> queryWrapper,
//                             @Param("createrUnitId") String createrUnitId);
    IPage<Blog> selectPage(IPage<Blog> page, Integer state);

    List<Blog> findByIds(List<Long> idList);

    //博客表关联用户表
    //参数加上@Param(Constants.WRAPPER),xml里加上${ew.customSqlSegment}可以实现复杂条件检索查询

    IPage<BlogVo> findByPage(IPage<BlogVo> page, @Param(Constants.WRAPPER) QueryWrapper<BlogVo> queryWrapper);

}