package com.zy.blog.dao;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.core.toolkit.Constants;
import com.zy.blog.dto.user.QueryUserParamDto;
import com.zy.blog.model.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper extends BaseMapper<User> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
//    int insert(User record);

    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jun 20 02:25:20 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(User record);

    List<User>  selectUserByParam(QueryUserParamDto queryUserParamDto);

    IPage<User> findByPage(IPage<User> page, @Param(Constants.WRAPPER) QueryWrapper<User> queryWrapper);

    User selectUser(String userName);
}